disabled_rules:
  - colon
  - comma
  - control_statement
  - force_cast
  - trailing_comma
  - opening_brace
  - identifier_name
  - type_body_length
  - file_length
  
opt_in_rules:
  - empty_count
  - missing_docs

reporter: xcode
warning_threshold: 15
